<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="assetqualifier" nsURI="http://www.example.org/assetqualifier"
    nsPrefix="assetqualifier">
  <eClassifiers xsi:type="ecore:EClass" name="AssetType">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Тип имущества. &#xD;&#xA;Базовая сущность для создания объекта имущества.&#xD;&#xA;Тип имущества определяется пользователем на основании первичных документов.&#xD;&#xA;Для всех объектов имущества данного типа могут быть использованы общие характеристики. &#xD;&#xA;Например: все на чем сидят имеет тип имущества &quot;Стул&quot; (независимо от того что часть из этих предметов может быть  креслами, табуретками, пуфиками и т.д.)&#xD;&#xA;Все объекты с типом имущества &quot;Стул&quot; имеют общие характеристики:&#xD;&#xA;производитель&#xD;&#xA;Цвет&#xD;&#xA;Материал изготовления&#xD;&#xA;направление использования"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NewEClass2"/>
</ecore:EPackage>
